// <auto-generated />
using GConta.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GConta.Infra.Data.Migrations
{
    [DbContext(typeof(GContaContext))]
    partial class GContaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GConta.Domain.Entities.Conta", b =>
                {
                    b.Property<int>("idConta")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataCriacao");

                    b.Property<bool>("flagAtivo");

                    b.Property<int>("idPessoa");

                    b.Property<decimal>("limiteSaqueDiario")
                        .HasColumnType("decimal(19, 2)");

                    b.Property<decimal>("saldo")
                        .HasColumnType("decimal(19, 2)");

                    b.Property<int>("tipoConta");

                    b.HasKey("idConta");

                    b.HasIndex("idPessoa");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("GConta.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("idPessoa")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<DateTime>("dataNascimento");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("idPessoa");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("GConta.Domain.Entities.Transacao", b =>
                {
                    b.Property<int>("idTransacao")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataTransacao");

                    b.Property<int>("idConta");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(19, 2)");

                    b.HasKey("idTransacao");

                    b.HasIndex("idConta");

                    b.ToTable("Transacao");
                });

            modelBuilder.Entity("GConta.Domain.Entities.Conta", b =>
                {
                    b.HasOne("GConta.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Contas")
                        .HasForeignKey("idPessoa")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GConta.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("GConta.Domain.Entities.Conta", "Conta")
                        .WithMany("Transacoes")
                        .HasForeignKey("idConta")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
